name: Build on Push
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Built JARs
          path: |
            build/libs/*.jar
            build/libs/merged/*.jar
            fabric/build/libs/*.jar
            forge/build/libs/*.jar
            common/build/libs/*.jar
